
DROP DATABASE IF EXISTS `scottfultondb`;
CREATE DATABASE `scottfultondb`;
USE `scottfultondb`;


DROP TABLE IF EXISTS `REQUESTS`;

CREATE TABLE `REQUESTS` (
	`RequestID` int(11) NOT NULL,
    PRIMARY KEY (RequestID)
);


DROP TABLE IF EXISTS `EQUIPMENT`;

CREATE TABLE `EQUIPMENT` (
	`EquipmentID` int(11) NOT NULL,
    `EquipmentName` varchar(10) DEFAULT NULL,
    PRIMARY KEY (EquipmentID)
);


DROP TABLE IF EXISTS `REQUESTS`;

CREATE TABLE `REQUESTS` (
	`RequestID` int(11) NOT NULL,
    
PRIMARY KEY (RequestID)
)


DROP TABLE IF EXISTS `REQUESTS`;

CREATE TABLE `REQUESTS` (
	`RequestID` int(11) NOT NULL,
    
PRIMARY KEY (RequestID)
)


DROP TABLE IF EXISTS `REQUESTS`;

CREATE TABLE `REQUESTS` (
	`RequestID` int(11) NOT NULL,
    
PRIMARY KEY (RequestID)
)